version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./sqls:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      MYSQL_USER: root
      MYSQL_DB_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: sample
    restart: always

volumes:
  db-data:
